import Head from "next/head";
import { Layout } from "../components/Layout";
import { Pokemon } from "../interfaces/pokemon";
import PokemonCard from "../components/PokemonCard";
import styled from "styled-components";

const List = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  grid-gap: 10px;
  align-items: center;
  text-align: center;
`;

const calculatePower = (pokemon: Pokemon) =>
  pokemon.hp +
  pokemon.attack +
  pokemon.defense +
  pokemon.special_attack +
  pokemon.special_defense +
  pokemon.speed;

const HomePage = ({ pokemons }: { pokemons: Pokemon[] }) => {
  return (
    <>
      <Head>
        <title>Technical test next.js and typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>Search</div>
        <input type="text"></input>
        <div>Power threshold</div>
        <input type="text"></input>
        <div>Count over threshold: </div>
        <div>Min: </div>
        <div>Max: </div>
      </div>
      <h1>Pokemon list</h1>
      <List>
        {pokemons.map((pokemon) => {
          return <PokemonCard pokemon={pokemon} />;
        })}
      </List>
    </>
  );
};

HomePage.getLayout = Layout;

export async function getServerSideProps() {
  try {
    const pokemons = await fetch("http://localhost:3000/api/pokemons").then(
      (resp) => resp.json()
    );
    return { props: { pokemons } };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}

export default HomePage;
